# Generated by Django 4.2.4 on 2023-09-02 20:48

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(help_text="ФИО", max_length=300)),
                (
                    "phone_number",
                    models.CharField(
                        help_text="+7(XXX)-XXX-XX-XX",
                        max_length=17,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\+7\\(\\d{3}\\)-\\d{3}-\\d{2}-\\d{2}$"
                            )
                        ],
                    ),
                ),
                (
                    "address",
                    models.CharField(help_text="Введите ваш адрес", max_length=300),
                ),
                (
                    "comment",
                    models.TextField(blank=True, help_text="Комментарий к заявке"),
                ),
                (
                    "application_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
            ],
        ),
    ]
