# Generated by Django 4.2.4 on 2023-10-08 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_carouselmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleWorkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ceiling_type', models.CharField(help_text='Тип натяжного потолка', max_length=150)),
                ('description', models.TextField(help_text='Описание')),
            ],
        ),
    ]
