# Generated by Django 4.2.4 on 2023-10-08 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_exampleworkmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='exampleworkmodel',
            name='image',
            field=models.ImageField(default=1, upload_to='images'),
            preserve_default=False,
        ),
    ]
